export const CHANGE_PASSWORD_LENGTH = 'CHANGE_PASSWORD_LENGTH';
export const GENERATE_PASSWORD = 'GENERATE_PASSWORD';
export const COPY_PASSWORD = "COPY_PASSWORD";
export const USE_SYMBOLS = 'USE_SYMBOLS';
export const USE_NUMBERS = 'USE_NUMBERS';